[package]
name = "keysas_lib"
version = "2.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha2 = "*"
anyhow = "*"
clap = "*"
walkdir ="*"
regex ="1.7.1"
log = "0.4"
simple_logger = "4.0"