[package]
name = "keysas-sign"
version = "1.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mbrman = "0.5" 
clap = { version = "4", default-features = false, features = ["std", "cargo"] }
minisign = "0.7"
anyhow = "1.0"
nom = "7"
libc = "0.2"
udev = "0.7"
openssl = "*"
openssl-sys = "*"